<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'id' => 9,
                'position' => 'cms',
                'label_id' => 8,
                'parent_id' => NULL,
                'name' => 'Developer Option',
                'name_bn' => 'ডেভেলপার অপশান',
                'system_name' => '',
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-bars',
                'status' => 1,
                'type' => 1,
                'order_by' => 2,
                'create_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-25 01:24:43',
                'updated_at' => '2024-12-02 17:14:59',
            ),
            1 => 
            array (
                'id' => 10,
                'position' => 'cms',
                'label_id' => 8,
                'parent_id' => 9,
                'name' => 'Menu Label',
                'name_bn' => 'মেনু স্তর',
                'system_name' => 'Menu Label',
                'route' => 'menu_label',
                'slug' => 'create',
                'icon' => '',
                'status' => 1,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-05-14 23:18:49',
                'updated_at' => '2024-05-15 15:31:48',
            ),
            2 => 
            array (
                'id' => 11,
                'position' => 'cms',
                'label_id' => 8,
                'parent_id' => 9,
                'name' => 'Menu',
                'name_bn' => 'মেনু',
                'system_name' => 'Menu',
                'route' => 'menu',
                'slug' => 'create',
                'icon' => '',
                'status' => 1,
                'type' => 2,
                'order_by' => 2,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-05-14 23:19:19',
                'updated_at' => '2024-05-15 15:32:30',
            ),
            3 => 
            array (
                'id' => 13,
                'position' => 'cms',
                'label_id' => 8,
                'parent_id' => NULL,
                'name' => 'Security',
                'name_bn' => 'সিকিউরিটি',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-lock',
                'status' => 1,
                'type' => 1,
                'order_by' => 2,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-05-14 23:53:32',
                'updated_at' => '2024-05-14 23:57:33',
            ),
            4 => 
            array (
                'id' => 15,
                'position' => 'cms',
                'label_id' => 8,
                'parent_id' => 13,
                'name' => 'Users',
                'name_bn' => 'ইউজার',
                'system_name' => 'Users',
                'route' => 'user',
                'slug' => 'create',
                'icon' => '',
                'status' => 1,
                'type' => 2,
                'order_by' => 2,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-05-14 23:58:53',
                'updated_at' => '2024-05-15 15:33:40',
            ),
            5 => 
            array (
                'id' => 22,
                'position' => 'cms',
                'label_id' => 7,
                'parent_id' => NULL,
                'name' => 'Dashboard',
                'name_bn' => 'ড্যাশবোর্ড',
                'system_name' => 'Dashboard',
                'route' => 'admin',
                'slug' => 'view',
                'icon' => 'fa fa-home',
                'status' => 1,
                'type' => 3,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-05 15:39:06',
                'updated_at' => '2024-12-05 15:40:34',
            ),
            6 => 
            array (
                'id' => 23,
                'position' => 'cms',
                'label_id' => 8,
                'parent_id' => 13,
                'name' => 'Role',
                'name_bn' => 'রোল',
                'system_name' => 'Role',
                'route' => 'role',
                'slug' => 'index',
                'icon' => '',
                'status' => 1,
                'type' => 2,
                'order_by' => 2,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-05 15:39:29',
                'updated_at' => '2024-12-05 15:43:54',
            ),
            7 => 
            array (
                'id' => 24,
                'position' => 'cms',
                'label_id' => 9,
                'parent_id' => NULL,
                'name' => 'Product Settings',
                'name_bn' => 'পণ্য সেটিংস',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-gears',
                'status' => 1,
                'type' => 1,
                'order_by' => 3,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-05 15:46:59',
                'updated_at' => '2024-12-05 15:46:59',
            ),
            8 => 
            array (
                'id' => 25,
                'position' => 'cms',
                'label_id' => 9,
                'parent_id' => 24,
                'name' => 'Product Item',
                'name_bn' => 'পণ্য আইটেম',
                'system_name' => 'Product Item',
                'route' => 'product_item',
                'slug' => 'index',
                'icon' => '',
                'status' => 1,
                'type' => 2,
                'order_by' => 14,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-05 15:48:31',
                'updated_at' => '2025-04-21 15:32:50',
            ),
            9 => 
            array (
                'id' => 26,
                'position' => 'cms',
                'label_id' => 9,
                'parent_id' => 24,
                'name' => 'Product Category',
                'name_bn' => 'প্রোডাক্ট ক্যাটাগরি',
                'system_name' => 'Product Category',
                'route' => 'product_category',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 2,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-07 17:03:33',
                'updated_at' => '2025-04-21 15:32:51',
            ),
            10 => 
            array (
                'id' => 27,
                'position' => 'cms',
                'label_id' => 9,
                'parent_id' => 24,
                'name' => 'Product Sub Category',
                'name_bn' => 'প্রোডাক্ট সাব ক্যাটাগরি',
                'system_name' => 'Product Sub Category',
                'route' => 'product_sub_category',
                'slug' => 'index',
                'icon' => '',
                'status' => 1,
                'type' => 2,
                'order_by' => 3,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-08 16:14:09',
                'updated_at' => '2025-04-21 15:32:59',
            ),
            11 => 
            array (
                'id' => 28,
                'position' => 'cms',
                'label_id' => 9,
                'parent_id' => 24,
                'name' => 'Product Brand',
                'name_bn' => 'প্রোডাক্ট ব্র্যান্ড',
                'system_name' => 'Product Brand',
                'route' => 'product_brands',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 3,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-09 12:10:02',
                'updated_at' => '2025-04-21 15:33:02',
            ),
            12 => 
            array (
                'id' => 29,
                'position' => 'cms',
                'label_id' => 9,
                'parent_id' => 24,
                'name' => 'Product Size',
                'name_bn' => 'প্রোডাক্ট সাইজ',
                'system_name' => 'Product Size',
                'route' => 'product_size',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 5,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-10 10:52:39',
                'updated_at' => '2025-04-21 15:33:02',
            ),
            13 => 
            array (
                'id' => 30,
                'position' => 'cms',
                'label_id' => 9,
                'parent_id' => 24,
                'name' => 'Product Color',
                'name_bn' => 'প্রোডাক্ট কালার',
                'system_name' => 'Product Color',
                'route' => 'product_color',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 6,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-10 10:53:32',
                'updated_at' => '2025-04-21 15:33:03',
            ),
            14 => 
            array (
                'id' => 31,
                'position' => 'cms',
                'label_id' => 9,
                'parent_id' => 24,
                'name' => 'Unit',
                'name_bn' => 'ইউনিট',
                'system_name' => 'Unit',
                'route' => 'unit',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 7,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-10 16:35:42',
                'updated_at' => '2025-04-21 15:46:44',
            ),
            15 => 
            array (
                'id' => 32,
                'position' => 'cms',
                'label_id' => 9,
                'parent_id' => 24,
                'name' => 'Sub Unit',
                'name_bn' => 'সাব ইউনিট',
                'system_name' => 'Sub Unit',
                'route' => 'sub_unit',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 8,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-10 16:36:30',
                'updated_at' => '2025-04-21 15:37:57',
            ),
            16 => 
            array (
                'id' => 33,
                'position' => 'cms',
                'label_id' => 9,
                'parent_id' => NULL,
                'name' => 'Product Information',
                'name_bn' => 'প্রোডাক্ট ইনফরমেশন',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa-solid fa-shop',
                'status' => 1,
                'type' => 1,
                'order_by' => 2,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-12 12:48:55',
                'updated_at' => '2025-04-21 15:37:59',
            ),
            17 => 
            array (
                'id' => 34,
                'position' => 'cms',
                'label_id' => 9,
                'parent_id' => 33,
                'name' => 'Product',
                'name_bn' => 'প্রোডাক্ট',
                'system_name' => 'Product Information',
                'route' => 'product_information',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-12 12:52:35',
                'updated_at' => '2025-04-21 15:38:00',
            ),
            18 => 
            array (
                'id' => 35,
                'position' => 'cms',
                'label_id' => 10,
                'parent_id' => NULL,
                'name' => 'Vendor Information',
                'name_bn' => 'ভেন্ডর ইনফরমেশন',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa-solid fa-person',
                'status' => 0,
                'type' => 1,
                'order_by' => 6,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-14 18:08:52',
                'updated_at' => '2025-02-18 19:21:13',
            ),
            19 => 
            array (
                'id' => 36,
                'position' => 'cms',
                'label_id' => 10,
                'parent_id' => 35,
                'name' => 'Vendor',
                'name_bn' => 'ভেন্ডর',
                'system_name' => 'Vendor',
                'route' => 'vendor',
                'slug' => 'index',
                'icon' => '',
                'status' => 0,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-14 18:09:24',
                'updated_at' => '2025-02-18 19:21:17',
            ),
            20 => 
            array (
                'id' => 37,
                'position' => 'cms',
                'label_id' => 11,
                'parent_id' => NULL,
                'name' => 'Delivery Charge Setup',
                'name_bn' => 'ডেলিভারি চার্জ সেটআপ',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa-solid fa-truck',
                'status' => 0,
                'type' => 1,
                'order_by' => 6,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-19 17:21:46',
                'updated_at' => '2025-02-18 19:21:25',
            ),
            21 => 
            array (
                'id' => 40,
                'position' => 'cms',
                'label_id' => 11,
                'parent_id' => 37,
                'name' => 'Division Setup',
                'name_bn' => 'বিভাগ সেটআপ',
                'system_name' => 'Division Setup',
                'route' => 'division_setup',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 0,
                'type' => 2,
                'order_by' => 3,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-19 18:03:12',
                'updated_at' => '2025-02-18 19:21:29',
            ),
            22 => 
            array (
                'id' => 42,
                'position' => 'cms',
                'label_id' => 11,
                'parent_id' => 37,
                'name' => 'District Setup',
                'name_bn' => 'জেলা সেটআপ',
                'system_name' => 'District Setup',
                'route' => 'district_setup',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 0,
                'type' => 2,
                'order_by' => 4,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-19 18:05:35',
                'updated_at' => '2025-02-18 19:21:40',
            ),
            23 => 
            array (
                'id' => 43,
                'position' => 'cms',
                'label_id' => 12,
                'parent_id' => NULL,
                'name' => 'Supplier',
                'name_bn' => 'সাপ্লাইয়ার',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-users',
                'status' => 0,
                'type' => 1,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-21 14:57:02',
                'updated_at' => '2025-02-18 19:21:44',
            ),
            24 => 
            array (
                'id' => 44,
                'position' => 'cms',
                'label_id' => 12,
                'parent_id' => 43,
                'name' => 'Supplier Info',
                'name_bn' => 'সাপ্লাইয়ার তথ্য',
                'system_name' => 'Supplier Info',
                'route' => 'supplier_info',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 0,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-21 14:57:44',
                'updated_at' => '2025-02-18 19:21:47',
            ),
            25 => 
            array (
                'id' => 45,
                'position' => 'cms',
                'label_id' => 11,
                'parent_id' => 37,
                'name' => 'Shipping Class',
                'name_bn' => 'শিপিং ক্লাস',
                'system_name' => 'Shipping Class',
                'route' => 'shipping_class',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 0,
                'type' => 2,
                'order_by' => 3,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-21 18:21:56',
                'updated_at' => '2025-02-18 19:21:47',
            ),
            26 => 
            array (
                'id' => 46,
                'position' => 'cms',
                'label_id' => 11,
                'parent_id' => 37,
                'name' => 'Thana Setup',
                'name_bn' => 'থানা সেটাপ',
                'system_name' => 'Thana Setup',
                'route' => 'thana_setup',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 0,
                'type' => 2,
                'order_by' => 4,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-22 11:59:23',
                'updated_at' => '2025-02-18 19:21:48',
            ),
            27 => 
            array (
                'id' => 47,
                'position' => 'cms',
                'label_id' => 11,
                'parent_id' => 37,
                'name' => 'Delivery Charge Add',
                'name_bn' => 'ডেলিভারি চার্জ যুক্তকরুন',
                'system_name' => 'Delivery Charge',
                'route' => 'delivary_charge',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 0,
                'type' => 2,
                'order_by' => 5,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-12-22 17:39:12',
                'updated_at' => '2025-02-18 19:21:52',
            ),
            28 => 
            array (
                'id' => 48,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => NULL,
                'name' => 'Company Information',
                'name_bn' => 'কোম্পানি তথ্য',
                'system_name' => '',
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-box',
                'status' => 1,
                'type' => 1,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-02-10 13:56:29',
                'updated_at' => '2025-02-17 12:36:01',
            ),
            29 => 
            array (
                'id' => 49,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 48,
                'name' => 'About Us',
                'name_bn' => 'আমাদের সম্পর্কে',
                'system_name' => 'About Us',
                'route' => 'about_us',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-02-10 13:57:07',
                'updated_at' => '2025-02-10 13:57:07',
            ),
            30 => 
            array (
                'id' => 50,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 48,
                'name' => 'Company Profile',
                'name_bn' => 'কোম্পানির প্রোফাইল',
                'system_name' => 'Company Profile',
                'route' => 'company_profile',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 2,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-02-10 17:36:51',
                'updated_at' => '2025-02-10 17:36:51',
            ),
            31 => 
            array (
                'id' => 51,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 48,
                'name' => 'Blog',
                'name_bn' => 'ব্লগ',
                'system_name' => 'Blog',
                'route' => 'blog',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 2,
                'create_by' => 3,
                'deleted_at' => '2025-02-11',
                'created_at' => '2025-02-11 15:02:10',
                'updated_at' => '2025-02-11 15:02:58',
            ),
            32 => 
            array (
                'id' => 52,
                'position' => 'cms',
                'label_id' => 7,
                'parent_id' => NULL,
                'name' => 'Car Information',
                'name_bn' => 'গাড়ির তথ্য',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-car',
                'status' => 1,
                'type' => 1,
                'order_by' => 4,
                'create_by' => 3,
                'deleted_at' => '2025-02-11',
                'created_at' => '2025-02-11 15:04:50',
                'updated_at' => '2025-02-11 16:44:32',
            ),
            33 => 
            array (
                'id' => 53,
                'position' => 'cms',
                'label_id' => 14,
                'parent_id' => NULL,
                'name' => 'Car Information',
                'name_bn' => 'গাড়ির তথ্য',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-box',
                'status' => 1,
                'type' => 1,
                'order_by' => 5,
                'create_by' => 3,
                'deleted_at' => '2025-02-13',
                'created_at' => '2025-02-11 15:06:00',
                'updated_at' => '2025-02-13 13:21:37',
            ),
            34 => 
            array (
                'id' => 54,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 48,
                'name' => 'Privacy Policy',
                'name_bn' => 'গোপনীয়তা নীতি',
                'system_name' => 'Privacy Policy',
                'route' => 'privacy_policy',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 3,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-02-11 16:45:50',
                'updated_at' => '2025-02-11 16:45:50',
            ),
            35 => 
            array (
                'id' => 55,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 48,
                'name' => 'Terms & Conditions',
                'name_bn' => 'শর্তাবলী',
                'system_name' => 'Terms & Conditions',
                'route' => 'terms_condition',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 4,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-02-11 17:07:37',
                'updated_at' => '2025-02-11 17:27:20',
            ),
            36 => 
            array (
                'id' => 56,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 48,
                'name' => 'Return & Refund Policy',
                'name_bn' => 'রিটার্ন এবং রিফান্ড নীতি',
                'system_name' => 'Return & Refund Policy',
                'route' => 'return_policy',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 5,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-02-11 17:09:23',
                'updated_at' => '2025-02-11 17:09:23',
            ),
            37 => 
            array (
                'id' => 57,
                'position' => 'cms',
                'label_id' => 14,
                'parent_id' => NULL,
                'name' => 'Service Information',
                'name_bn' => 'সার্ভিস তথ্য',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-box',
                'status' => 1,
                'type' => 1,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-02-13 13:23:18',
                'updated_at' => '2025-02-13 13:23:18',
            ),
            38 => 
            array (
                'id' => 58,
                'position' => 'cms',
                'label_id' => 14,
                'parent_id' => 57,
                'name' => 'Create Service',
                'name_bn' => 'সার্ভিস তৈরি করুন',
                'system_name' => 'Service',
                'route' => 'create_service',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => '2025-03-02',
                'created_at' => '2025-02-13 13:27:23',
                'updated_at' => '2025-03-02 14:13:06',
            ),
            39 => 
            array (
                'id' => 59,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 85,
                'name' => 'Photo Gallery',
                'name_bn' => 'ফটো গ্যালারী',
                'system_name' => 'Photo Gallery',
                'route' => 'photo_gallery',
                'slug' => 'index',
                'icon' => '',
                'status' => 1,
                'type' => 2,
                'order_by' => 6,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-02-13 17:44:39',
                'updated_at' => '2025-04-23 11:36:09',
            ),
            40 => 
            array (
                'id' => 60,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 85,
                'name' => 'Video Gallery',
                'name_bn' => 'ভিডিও গ্যালারী',
                'system_name' => 'Video Gallery',
                'route' => 'video_gallery',
                'slug' => 'index',
                'icon' => '',
                'status' => 1,
                'type' => 2,
                'order_by' => 7,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-02-13 17:45:04',
                'updated_at' => '2025-04-23 11:37:00',
            ),
            41 => 
            array (
                'id' => 61,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => NULL,
                'name' => 'Employee Information',
                'name_bn' => 'কর্মকর্তা/কর্মচারী',
                'system_name' => '',
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-box',
                'status' => 0,
                'type' => 1,
                'order_by' => 2,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-02-16 11:14:20',
                'updated_at' => '2025-03-17 15:17:54',
            ),
            42 => 
            array (
                'id' => 62,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 61,
                'name' => 'Create Employee',
                'name_bn' => 'কর্মকর্তা/কর্মচারী তৈরি করুন',
                'system_name' => 'Create Employee',
                'route' => 'create_employee',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 0,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-02-16 11:15:27',
                'updated_at' => '2025-03-17 15:17:56',
            ),
            43 => 
            array (
                'id' => 63,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => NULL,
                'name' => 'Clients Information',
                'name_bn' => 'ক্লায়েন্টস',
                'system_name' => '',
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-box',
                'status' => 0,
                'type' => 1,
                'order_by' => 3,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-02-16 11:20:11',
                'updated_at' => '2025-03-17 15:18:19',
            ),
            44 => 
            array (
                'id' => 64,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 63,
                'name' => 'Create Clients',
                'name_bn' => 'ক্লায়েন্টস তৈরি করুন',
                'system_name' => 'Create Clients',
                'route' => 'create_clients',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 0,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-02-16 11:20:59',
                'updated_at' => '2025-03-17 15:18:21',
            ),
            45 => 
            array (
                'id' => 65,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => NULL,
                'name' => 'Blogs',
                'name_bn' => 'ব্লগ',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-box',
                'status' => 1,
                'type' => 1,
                'order_by' => 4,
                'create_by' => 3,
                'deleted_at' => '2025-02-17',
                'created_at' => '2025-02-16 17:03:01',
                'updated_at' => '2025-02-17 12:18:45',
            ),
            46 => 
            array (
                'id' => 66,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => NULL,
                'name' => 'News & Events',
                'name_bn' => 'নিউজ ও ইভেন্ট',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-box',
                'status' => 1,
                'type' => 1,
                'order_by' => 5,
                'create_by' => 3,
                'deleted_at' => '2025-02-16',
                'created_at' => '2025-02-16 17:04:08',
                'updated_at' => '2025-02-16 17:07:35',
            ),
            47 => 
            array (
                'id' => 67,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 65,
                'name' => 'Create Blogs',
                'name_bn' => 'ব্লগ তৈরি করুন',
                'system_name' => 'Create Blogs',
                'route' => 'create_blogs',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => '2025-02-17',
                'created_at' => '2025-02-16 17:05:01',
                'updated_at' => '2025-02-17 12:18:38',
            ),
            48 => 
            array (
                'id' => 68,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 66,
                'name' => 'Create News & Events',
                'name_bn' => 'নিউজ ও ইভেন্ট তৈরি করুন',
                'system_name' => 'Create News & Events',
                'route' => 'newsevents',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => '2025-02-16',
                'created_at' => '2025-02-16 17:06:06',
                'updated_at' => '2025-02-16 17:07:26',
            ),
            49 => 
            array (
                'id' => 69,
                'position' => 'cms',
                'label_id' => 15,
                'parent_id' => NULL,
                'name' => 'Blogs Information',
                'name_bn' => 'ব্লগ',
                'system_name' => '',
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-box',
                'status' => 0,
                'type' => 1,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-02-17 12:19:31',
                'updated_at' => '2025-04-21 18:04:03',
            ),
            50 => 
            array (
                'id' => 70,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 81,
                'name' => 'Create Blogs',
                'name_bn' => 'ব্লগ তৈরি করুন',
                'system_name' => 'Create Blogs',
                'route' => 'create_blogs',
                'slug' => 'index',
                'icon' => '',
                'status' => 1,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-02-17 12:20:41',
                'updated_at' => '2025-04-21 18:02:36',
            ),
            51 => 
            array (
                'id' => 71,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 81,
                'name' => 'Message From Website',
                'name_bn' => 'ওয়েবসাইট থেকে বার্তা',
                'system_name' => 'Message',
                'route' => 'message',
                'slug' => 'index',
                'icon' => '',
                'status' => 1,
                'type' => 2,
                'order_by' => 8,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-02-17 12:37:39',
                'updated_at' => '2025-03-11 15:16:55',
            ),
            52 => 
            array (
                'id' => 72,
                'position' => 'cms',
                'label_id' => 14,
                'parent_id' => 57,
                'name' => 'Service Category',
                'name_bn' => 'সার্ভিস ক্যাটাগরি',
                'system_name' => 'Service Category',
                'route' => 'service_category',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-03-02 14:09:10',
                'updated_at' => '2025-03-25 11:07:14',
            ),
            53 => 
            array (
                'id' => 73,
                'position' => 'cms',
                'label_id' => 14,
                'parent_id' => 57,
                'name' => 'Create Service',
                'name_bn' => 'সার্ভিস তৈরি করুন',
                'system_name' => 'Service',
                'route' => 'create_service',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 2,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-03-02 14:14:23',
                'updated_at' => '2025-03-02 14:14:23',
            ),
            54 => 
            array (
                'id' => 74,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 80,
                'name' => 'Create Ads',
                'name_bn' => 'বিজ্ঞাপন তৈরি করুন',
                'system_name' => 'Create Ads',
                'route' => 'create_ads',
                'slug' => 'index',
                'icon' => '',
                'status' => 0,
                'type' => 2,
                'order_by' => 9,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-03-08 00:07:12',
                'updated_at' => '2025-03-17 15:17:43',
            ),
            55 => 
            array (
                'id' => 75,
                'position' => 'cms',
                'label_id' => 14,
                'parent_id' => NULL,
                'name' => 'Booking Information',
                'name_bn' => 'বুকিং ইনফরমেশন',
                'system_name' => '',
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-box',
                'status' => 0,
                'type' => 1,
                'order_by' => 2,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-03-09 15:00:10',
                'updated_at' => '2025-03-17 11:46:42',
            ),
            56 => 
            array (
                'id' => 76,
                'position' => 'cms',
                'label_id' => 14,
                'parent_id' => 75,
                'name' => 'Bookings',
                'name_bn' => 'বুকিং লিস্ট',
                'system_name' => 'Bookings',
                'route' => 'bookings',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 0,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-03-09 15:09:46',
                'updated_at' => '2025-03-17 11:46:39',
            ),
            57 => 
            array (
                'id' => 77,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 81,
                'name' => 'Faq',
                'name_bn' => 'প্রশ্ন',
                'system_name' => 'Faq',
                'route' => 'faq',
                'slug' => 'index',
                'icon' => '',
                'status' => 0,
                'type' => 2,
                'order_by' => 3,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-03-09 16:41:01',
                'updated_at' => '2025-03-17 12:42:31',
            ),
            58 => 
            array (
                'id' => 78,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 48,
                'name' => 'Career',
                'name_bn' => 'ক্যারিয়ার',
                'system_name' => 'Career',
                'route' => 'create_career',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 10,
                'create_by' => 3,
                'deleted_at' => '2025-03-17',
                'created_at' => '2025-03-10 14:13:57',
                'updated_at' => '2025-03-17 11:46:07',
            ),
            59 => 
            array (
                'id' => 79,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 48,
                'name' => 'Service Guarantee',
                'name_bn' => 'সার্ভিস গ্যারান্টি',
                'system_name' => 'Service Guarantee',
                'route' => 'service_guarantee',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 11,
                'create_by' => 3,
                'deleted_at' => '2025-03-17',
                'created_at' => '2025-03-11 01:39:58',
                'updated_at' => '2025-03-17 11:46:51',
            ),
            60 => 
            array (
                'id' => 80,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => NULL,
                'name' => 'Ads Information',
                'name_bn' => 'বিজ্ঞাপন ইনফরমেশন',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-box',
                'status' => 0,
                'type' => 1,
                'order_by' => 4,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-03-11 01:41:44',
                'updated_at' => '2025-03-17 15:17:45',
            ),
            61 => 
            array (
                'id' => 81,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => NULL,
                'name' => 'Home Page Data',
                'name_bn' => 'হোম পেইজ ডাটা',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-box',
                'status' => 1,
                'type' => 1,
                'order_by' => 5,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-03-11 15:16:23',
                'updated_at' => '2025-03-11 15:16:23',
            ),
            62 => 
            array (
                'id' => 82,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 81,
                'name' => 'Reviews',
                'name_bn' => 'রিভিউস',
                'system_name' => 'Reviews',
                'route' => 'reviews',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 0,
                'type' => 2,
                'order_by' => 2,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-03-11 15:18:38',
                'updated_at' => '2025-03-17 12:42:41',
            ),
            63 => 
            array (
                'id' => 83,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 81,
                'name' => 'Create News & Events',
                'name_bn' => 'নিউজ ও ইভেন্ট তৈরি করুন',
                'system_name' => 'News & Events',
                'route' => 'newsevents',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-04-21 19:07:01',
                'updated_at' => '2025-04-21 19:07:01',
            ),
            64 => 
            array (
                'id' => 84,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 81,
                'name' => 'Career',
                'name_bn' => 'ক্যারিয়ার',
                'system_name' => 'Career',
                'route' => 'create_career',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 4,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-04-22 19:07:30',
                'updated_at' => '2025-04-22 19:07:30',
            ),
            65 => 
            array (
                'id' => 85,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => NULL,
                'name' => 'Gallery',
                'name_bn' => 'গ্যালারী',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-box',
                'status' => 1,
                'type' => 1,
                'order_by' => 3,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-04-23 11:35:35',
                'updated_at' => '2025-04-23 11:35:35',
            ),
            66 => 
            array (
                'id' => 86,
                'position' => 'cms',
                'label_id' => 13,
                'parent_id' => 48,
                'name' => 'Mission & Vision',
                'name_bn' => 'লক্ষ্য এবং উদ্দেশ্য',
                'system_name' => 'Mission Vision',
                'route' => 'mission_vision',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 6,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-04-23 13:06:07',
                'updated_at' => '2025-04-23 13:06:07',
            ),
        ));
        
        
    }
}